# Generated by Django 5.2.8 on 2025-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nome',
            field=models.IntegerField(choices=[(1, 'Admin'), (3, 'Secretário'), (2, 'Diretor'), (4, 'Estudante')], max_length=90),
        ),
    ]
