# Generated by Django 6.0.3 on 2026-03-26 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('certificado', 'Certificado de Habilitações'), ('declaracao_matricula', 'Declaração de Matrícula'), ('declaracao_frequencia', 'Declaração de Frequência'), ('declaracao_notas', 'Declaração de Notas'), ('declaracao_conclusao', 'Declaração de Conclusão de Curso'), ('historico', 'Histórico Escolar')], max_length=40, verbose_name='Tipo de Documento')),
                ('nome', models.CharField(help_text='Nome interno para identificar este template.', max_length=200, verbose_name='Nome do Template')),
                ('e_padrao', models.BooleanField(default=False, help_text='Se marcado, é o template usado por omissão para este tipo.', verbose_name='É Padrão')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cabecalho_titulo', models.CharField(default='CERTIFICADO DE HABILITAÇÕES', help_text='Texto principal em destaque no topo. Suporta variáveis.', max_length=300, verbose_name='Título do Documento')),
                ('cabecalho_subtitulo', models.CharField(blank=True, help_text="Ex: 'REPÚBLICA DE ANGOLA - MINISTÉRIO DA EDUCAÇÃO'", max_length=300, verbose_name='Subtítulo')),
                ('mostrar_brasao', models.BooleanField(default=True, verbose_name='Mostrar Brasão/Logótipo')),
                ('mostrar_cabecalho_escola', models.BooleanField(default=True, verbose_name='Mostrar Cabeçalho da Escola')),
                ('texto_abertura', models.TextField(default='O Director(a) da {{escola_nome}}, no uso das suas competências e nos termos da legislação em vigor, certifica que:', help_text='Parágrafo introdutório. Suporta variáveis {{...}}.', verbose_name='Texto de Abertura')),
                ('texto_identificacao', models.TextField(default='{{aluno_nome}}, filho(a) de {{aluno_nome_pai}} e de {{aluno_nome_mae}}, nascido(a) em {{aluno_data_nasc}}, natural de {{aluno_naturalidade}}, portador(a) do Bilhete de Identidade n.º {{aluno_bi}},', help_text='Identificação do aluno. Suporta variáveis {{...}}.', verbose_name='Bloco de Identificação')),
                ('texto_corpo', models.TextField(default='concluiu com aproveitamento o {{classe}} do Ensino Secundário, Curso de {{curso}}, no ano lectivo {{ano_lectivo}}, tendo obtido a classificação final de {{nota_final_num}} ({{nota_final_extenso}}) valores, situação: {{situacao_final}}.', help_text='Texto central do documento. Suporta variáveis {{...}}.', verbose_name='Corpo do Documento')),
                ('texto_rodape', models.TextField(blank=True, default='O presente {{tipo_documento}} é passado a pedido do(a) interessado(a) e para os fins que o(a) mesmo(a) entender convenientes.', help_text='Parágrafo final antes das assinaturas. Suporta variáveis {{...}}.', verbose_name='Texto de Rodapé')),
                ('incluir_tabela_notas', models.BooleanField(default=True, verbose_name='Incluir Tabela de Notas')),
                ('texto_antes_tabela', models.CharField(blank=True, default='Classificações obtidas:', max_length=300, verbose_name='Texto antes da Tabela')),
                ('local_emissao', models.CharField(default='{{escola_municipio}}', help_text="Ex: 'Luanda'. Pode usar {{escola_municipio}}.", max_length=100, verbose_name='Local de Emissão')),
                ('texto_data_emissao', models.CharField(default='{{local_emissao}}, {{data_emissao}}', help_text='Formato da linha de data e local.', max_length=200, verbose_name='Formato da Data')),
                ('orientacao', models.CharField(choices=[('retrato', 'Retrato (Portrait)'), ('paisagem', 'Paisagem (Landscape)')], default='retrato', max_length=10, verbose_name='Orientação')),
                ('margem_topo', models.IntegerField(default=2, verbose_name='Margem Topo (cm)')),
                ('margem_lateral', models.IntegerField(default=2, verbose_name='Margem Lateral (cm)')),
                ('tamanho_fonte_corpo', models.IntegerField(default=12, help_text='Em pontos (pt). Recomendado: 11-13.', verbose_name='Tamanho da Fonte (corpo)')),
                ('usar_borda', models.BooleanField(default=True, verbose_name='Usar Borda Decorativa')),
                ('prefixo_numeracao', models.CharField(blank=True, help_text="Ex: 'CERT', 'DECL'. O número será: CERT-2024-0001.", max_length=20, verbose_name='Prefixo de Numeração')),
                ('contador_atual', models.PositiveIntegerField(default=0, verbose_name='Contador Actual')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_documentos', to='academico.tenantescola', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Template de Documento',
                'verbose_name_plural': 'Templates de Documentos',
                'db_table': 'template_documento',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número do Documento')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('emitido', 'Emitido'), ('anulado', 'Anulado'), ('segunda_via', 'Segunda Via')], db_index=True, default='rascunho', max_length=20, verbose_name='Estado')),
                ('conteudo_html', models.TextField(blank=True, help_text='Snapshot do documento gerado (para reimpressão idêntica).', verbose_name='Conteúdo HTML')),
                ('dados_snapshot', models.JSONField(default=dict, help_text='Snapshot de todos os dados usados na geração.', verbose_name='Dados no momento da Emissão')),
                ('motivo_anulacao', models.TextField(blank=True, verbose_name='Motivo de Anulação')),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_gerados', to='academico.aluno', verbose_name='Aluno')),
                ('ano_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_gerados', to='academico.anolectivo', verbose_name='Ano Lectivo')),
                ('documento_original', models.ForeignKey(blank=True, help_text='Preenchido quando se trata de uma 2ª via.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segundas_vias', to='documentos.documentogerado', verbose_name='Documento Original')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to='academico.tenantescola', verbose_name='Escola')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='academico.matricula', verbose_name='Matrícula')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_gerados', to='documentos.templatedocumento', verbose_name='Template Utilizado')),
            ],
            options={
                'verbose_name': 'Documento Gerado',
                'verbose_name_plural': 'Documentos Gerados',
                'db_table': 'documento_gerado',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cargo', models.CharField(choices=[('director', 'Director(a)'), ('subdirector', 'Subdirector(a) Pedagógico(a)'), ('secretario', 'Chefe de Secretaria'), ('outro', 'Outro')], max_length=20, verbose_name='Cargo')),
                ('cargo_customizado', models.CharField(blank=True, help_text='Preenchido quando cargo = Outro.', max_length=100, verbose_name='Cargo Customizado')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_documentos', to='academico.tenantescola', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Assinatura de Documento',
                'verbose_name_plural': 'Assinaturas de Documentos',
                'db_table': 'assinatura_documento',
                'ordering': ['escola', 'ordem'],
                'indexes': [models.Index(fields=['escola', 'activo'], name='idx_assinatura_escola_activo')],
            },
        ),
        migrations.AddIndex(
            model_name='templatedocumento',
            index=models.Index(fields=['escola', 'tipo', 'activo'], name='idx_template_escola_tipo'),
        ),
        migrations.AddIndex(
            model_name='templatedocumento',
            index=models.Index(fields=['escola', 'e_padrao'], name='idx_template_padrao'),
        ),
        migrations.AddIndex(
            model_name='documentogerado',
            index=models.Index(fields=['escola', 'status'], name='idx_docger_escola_status'),
        ),
        migrations.AddIndex(
            model_name='documentogerado',
            index=models.Index(fields=['aluno', 'template'], name='idx_docger_aluno_template'),
        ),
        migrations.AddIndex(
            model_name='documentogerado',
            index=models.Index(fields=['numero_documento'], name='idx_docger_numero'),
        ),
        migrations.AddIndex(
            model_name='documentogerado',
            index=models.Index(fields=['escola', 'data_emissao'], name='idx_docger_escola_data'),
        ),
    ]
