# Generated by Django 5.2.8 on 2025-12-01 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200)),
                ('bi', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('nacionalidade', models.CharField(default='Angolana', max_length=50)),
                ('especialidade', models.CharField(max_length=100)),
                ('nivel_academico', models.CharField(choices=[('Bacharel', 'Bacharel'), ('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=20)),
                ('instituicao_formacao', models.CharField(max_length=200)),
                ('anos_experiencia', models.IntegerField(default=0)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('endereco', models.TextField()),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Licença', 'Licença'), ('Demitido', 'Demitido')], default='Activo', max_length=20)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tenantescola')),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'db_table': 'diretor',
            },
        ),
    ]
