# Generated by Django 5.2.8 on 2025-12-01 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_aluno_utilizador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco_completo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='encarregadoeducacao',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encarregadoeducacao',
            name='utilizador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='anos_experiencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='instituicao_formacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Contratado', 'Contratado'), ('Estagiário', 'Estagiário')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='utilizador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
