# Generated by Django 5.2.8 on 2025-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_aluno_bairro_alter_aluno_endereco_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(auto_now_add=True),
        ),
    ]
