# Generated by Django 5.2.8 on 2025-12-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_matricula_data_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
