# Generated by Django 5.2.8 on 2025-12-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_matricula_motivo_cancelamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='nacionalidade',
        ),
        migrations.DeleteModel(
            name='FormacaoProfessor',
        ),
    ]
