# Generated by Django 5.2.8 on 2025-12-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_remove_professor_cv_remove_professor_data_admissao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='salario_base',
        ),
    ]
