# Generated by Django 5.2.8 on 2025-12-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_alter_professor_carga_horaria_semanal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='academico.tenantescola'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='academico.tenantescola'),
        ),
        migrations.AddField(
            model_name='classe',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academico.tenantescola'),
        ),
        migrations.AddField(
            model_name='contaaluno',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas', to='academico.tenantescola'),
        ),
        migrations.AddField(
            model_name='documentoaluno',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='academico.tenantescola'),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='academico.tenantescola'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='academico.tenantescola'),
        ),
        migrations.AddField(
            model_name='nota',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='academico.tenantescola'),
        ),
    ]
