# Generated by Django 5.2.8 on 2025-12-01 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioConfiguracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Académico', 'Académico'), ('Financeiro', 'Financeiro'), ('Estatístico', 'Estatístico'), ('INIDE', 'INIDE')], max_length=50)),
                ('template', models.TextField(blank=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('formato_saida', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('agendamento', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tenantescola')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioGerado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('parametros_usados', models.JSONField(blank=True, default=dict)),
                ('arquivo', models.FileField(upload_to='relatorios/gerados/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.relatorioconfiguracao')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tenantescola')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
