# Generated by Django 5.2.8 on 2025-12-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsistema',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.tenantescola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.tenantescola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosistema',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.tenantescola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilacesso',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.tenantescola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilizador',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.tenantescola'),
            preserve_default=False,
        ),
    ]
