# Generated by Django 5.2.8 on 2025-12-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('authenticate', '0002_backupsistema_escola_logauditoria_escola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.tenantescola'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='tipo_utilizador',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('aluno', 'Aluno'), ('professor', 'Professor'), ('chefe_secretara', 'Chefe da secretaria'), ('ecarregado', 'Encarregado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='verificado_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='verificado_telefone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
