# Generated by Django 5.2.8 on 2025-12-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_utilizador_escola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='tipo_utilizador',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('aluno', 'Aluno'), ('diretor', 'Director'), ('professor', 'Professor'), ('chefe_secretara', 'Chefe da secretaria'), ('ecarregado', 'Encarregado')], max_length=20, null=True),
        ),
    ]
