# Generated by Django 5.2.8 on 2025-12-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_utilizador_tipo_utilizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='bi',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='telefone',
        ),
    ]
